# Generated by Django 6.0.2 on 2026-03-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(default='👤', max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('pending', 'Kutilmoqda'), ('vip', 'VIP')], default='active', max_length=20)),
                ('category', models.CharField(blank=True, choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('vip', 'VIP'), ('korporativ', 'Korporativ'), ('online', 'Online')], max_length=50)),
                ('city', models.CharField(blank=True, choices=[('toshkent', 'Toshkent'), ('samarqand', 'Samarqand'), ('buxoro', 'Buxoro'), ('namangan', 'Namangan'), ('andijon', 'Andijon'), ('fargona', "Farg'ona"), ('qashqadaryo', 'Qashqadaryo'), ('surxondaryo', 'Surxondaryo')], max_length=50)),
            ],
        ),
    ]
