# Generated by Django 6.0.2 on 2026-03-02 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Customer',
        ),
    ]
