# Generated by Django 6.0.2 on 2026-03-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0002_rename_client_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notice',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
