# Generated by Django 6.0.2 on 2026-03-02 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0003_customer_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='avatar',
        ),
    ]
